core: validate version

diff --git a/.github/workflows/versionupdate.yml b/.github/workflows/versionupdate.yml
--- a/.github/workflows/versionupdate.yml
+++ b/.github/workflows/versionupdate.yml
@@ -11,13 +11,18 @@ jobs:
         uses: actions/checkout@v4
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-
+      
       - name: Update Homebrew formula
         run: |
           VERSION="${{ github.event.client_payload.version }}"
           VERSION=${VERSION#v}
 
           TARBALL_URL="https://github.com/alesbrelih/gitlab-ci-ls/archive/refs/tags/${VERSION}.tar.gz"
+          if ! curl -sf --head "$TARBALL_URL" > /dev/null; then
+            echo "Tarball not found or not accessible: $TARBALL_URL"
+            exit 1
+          fi
+
           NEW_SHA256=$(curl -sL "$TARBALL_URL" | sha256sum | cut -d' ' -f1)
 
           sed -i "s|url \".*\"|url \"$TARBALL_URL\"|" Formula/gitlab-ci-ls.rb
@@ -27,3 +32,11 @@ jobs:
           echo "New SHA256: $NEW_SHA256"
           echo "New File"
           cat Formula/gitlab-ci-ls.rb
+
+      - name: Commit and push
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add GitlabCiLs.rb
+          git commit -m "Update GitlabCiLs to version ${{ github.event.client_payload.version }}"
+          git push
